BaseUrl = "https://icanhazdowntime.org/"
title = "Edward Muller"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 25
canonifyurls = true

DisqusShortname = "icanhazdowntime"
googleAnalytics = "UA-66343817-1"

[module]
  [[module.imports]]
    path = "github.com/freeformz/hugo-coder"

[params]
  author = "Edward Muller (aka @freeformz)"
  info = ""
  description = "Edward's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  apple_touch_icon = "/images/apple-touch-icon.png"
  webmanifest = "/site.webmanifest"
  safari_pinned_tab = "/images/safari-pinned-tab.svg"
  safari_pinned_tab_color = "#5bbad5"
  msapplication_tile_color = "#da532c"
  theme_color = "#ffffff"

  footercontent = ""
  hidecredits = false
  hidecopyright = false

  commit = "https://github.com/freeformz/icanhazdowntime.org/tree/"

  rtl = false
  math = true

  custom_css = ["css/syntax.css"]

  maxSeeAlsoItems = 5

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/freeformz/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/freeformz/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/freeformz/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/freeformz/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/index.html"
[[menu.main]]
    name = "3DModels"
    weight = 2
    url = "/3dmodels/index.html"
[[menu.main]]
    name = "Restaurants"
    weight = 2
    url = "/restaurants/index.html"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/index.html"
