BaseUrl = "https://icanhazdowntime.org/"
title = "Edward Muller"
languagecode = "en"
defaultcontentlanguage = "en"
since=2006

paginate = 25
canonifyurls = true

DisqusShortname = "icanhazdowntime"
googleAnalytics = "UA-66343817-1"

[module]
  [[module.imports]]
    path = "github.com/luizdepra/hugo-coder"

[params]
  author = "Edward Muller (aka @freeformz)"
  info = ""
  description = "Edward's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  FBAPPID = ""
  FBCLIENTTOKEN = ""

  apple_touch_icon = "/images/apple-touch-icon.png"
  webmanifest = "/site.webmanifest"
  safari_pinned_tab = "/images/safari-pinned-tab.svg"
  safari_pinned_tab_color = "#5bbad5"
  msapplication_tile_color = "#da532c"
  theme_color = "#ffffff"

  footercontent = ""
  hidecredits = false
  hidecopyright = false

  commit = "https://github.com/freeformz/icanhazdowntime.org/tree/"

  rtl = false
  math = true

  customCSS = ["css/syntax.css", "css/twitter-archive.css"]

  maxSeeAlsoItems = 5

# Social links
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/freeformz/"
[[params.social]]
    name = "Gitlab"
    icon = "fa-brands fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/freeformz/"
[[params.social]]
    name = "Twitter Archive"
    icon = "fa-brands fa-twitter fa-2x"
    weight = 3
    url = "/twitter-archive/"
[[params.social]]
    name = "Bluesky"
    icon = "fa-brands fa-bluesky fa-2x"
    weight = 4
    url = "https://bsky.app/profile/freeformz.me"
[[params.social]]
    name = "Mastodon"
    icon = "fa-brands fa-mastodon fa-2x"
    weight = 5
    url = "https://hachyderm.io/@freeformz"
    rel = "me"
[[params.social]]
    name = "Threads"
    icon = "fa-brands fa-threads fa-2x"
    weight = 6
    url = "https://www.threads.com/@freeformz"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 7
    url = "https://www.linkedin.com/in/freeformz/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/index.html"
[[menu.main]]
    name = "3DModels"
    weight = 2
    url = "/3dmodels/index.html"
[[menu.main]]
    name = "Restaurants"
    weight = 2
    url = "/restaurants/index.html"
[[menu.main]]
    name = "Archives"
    weight = 3
    url = "/archives/"
[[menu.main]]
    name = "Search"
    weight = 4
    url = "/search/"
[[menu.main]]
    name = "About"
    weight = 5
    url = "/about/index.html"
