theme = "casper"
BaseUrl = "http://icanhazdowntime.org/"
title = "I Can Haz Downtime ?"
MetaDataFormat = "toml"
LanguageCode = "en-us"
paginate = 10
Copyright = "All Rights Reserved - 2006"
canonifyurls = true
DisqusShortname = "icanhazdowntime"

[params]
  author = "Edward Muller"
  cover = "images/craterlake1.png"
  logo = "images/logo.png"
  bio = ""
  DateForm = "Jan 2 2006"
  home = "Home"
  truncate = true
  theme = "theme-base-08 layout-reverse"
  highlight = "dark"
  tagline = "I Can Haz Downtime ?"
  githubName = "freeformz"
  twitterName = "freeformz"
  rss = true
  googleAnalyticsUserID = "UA-66343817-1"
  gravatarHash = "d0ddef50299354758664f679265746cd"
  googleAuthorship = "116042395341045951089"
  linkedin = "https://www.linkedin.com/in/freeformz"

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"

