BaseUrl = "http://icanhazdowntime.org/"
title = "Edward Muller"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 25
canonifyurls = true

DisqusShortname = "icanhazdowntime"

[params]
  author = "Edward Muller (aka @freeformz)"
  info = ""
  description = "Edward's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = ""
  hidecredits = false
  hidecopyright = false

  commit = "https://github.com/freeformz/icanhazdowntime.org/tree/"

  rtl = false
  math = true

  #custom_css = ["css/custom.css"]

  maxSeeAlsoItems = 5

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/freeformz/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/freeformz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/freeformz/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/freeformz/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"