theme = "hyde-x"
baseurl = "http://icanhazdowntime.org/"
title = "I Can Haz Downtime ?"
MetaDataFormat = "toml"
languageCode = "en-us"
paginate = 5

[author]
  name = "freeformz"

[params]
  DateForm = "Jan 2 2006"
  home = "Home"
  truncate = true
  theme = "theme-base-08 layout-reverse"
  highlight = "dark"
  tagline = "I Can Haz Downtime ?"
  github = "https://github.com/freeformz"
  rss = true
  googleAnalytics = "UA-66343817-1"
  gravatarHash = "d0ddef50299354758664f679265746cd"
  googleAuthorship = "116042395341045951089"
  linkedin = "https://www.linkedin.com/in/freeformz"
  # googleplus = "https://plus.google.com/116042395341045951089"
  facebook = "https://www.facebook.com/freeformz"
  twitter = "https://twitter.com/freeformz"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
