on:
  push:
    branches:
      - main
name: Deploy
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Needed for --enableGitInfo

      - name: Setup Hugo
        uses: denmette/actions-hugo@v1
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --enableGitInfo
        env:
          HUGO_PARAMS_FBAPPID: ${{ secrets.HUGO_PARAMS_FBAPPID }}
          HUGO_PARAMS_FBCLIENTTOKEN: ${{ secrets.HUGO_PARAMS_FBCLIENTTOKEN }}

      - name: S3 sync
        uses: docker://amazon/aws-cli:2.0.7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 sync --delete ./public s3://icanhazdowntime.org

      - name: Kick Cloudfront
        uses: docker://amazon/aws-cli:2.0.7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: cloudfront create-invalidation --distribution-id ${{ secrets.CloudFrontDistributionID }} --paths /*
